name: public_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^2.0.0
  flutter_svg: ^0.19.3
  http: ^0.13.0
  maps_launcher: ^1.2.2+2
  pin_code_fields: ^7.0.0
  geolocator: 6.2.1
  dio:
  shared_preferences: ^2.0.5
  fluttertoast:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/logo/
